### ISSUE TITLE
Tracking updates for 11.1 and 11.2

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/cudatoolkit-feedstock#47]
Since there are multiple PRs across different repos involved, I will try to summarize the status here for visibility:

## 11.1

- [X] `cudatoolkit` - see https://github.com/conda-forge/cudatoolkit-feedstock/pull/39
- [x] `nvcc` - see https://github.com/conda-forge/nvcc-feedstock/pull/63
- [X] Docker image - see https://github.com/conda-forge/docker-images/pull/163
- [X] Windows installer - see https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/131
- [x] Migrator - see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1162

## 11.2

- [x] `cudatoolkit` - see https://github.com/conda-forge/cudatoolkit-feedstock/pull/46
- [x] `nvcc` - see https://github.com/conda-forge/nvcc-feedstock/pull/63
- [x] Docker image - see https://github.com/conda-forge/docker-images/pull/171
- [x] Windows installer - see https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/141
- [x] Migrator - see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1162

### 11.2.1

> A patch release should only require these three repositories updated. `nvcc` and the migrator operate at the major.minor level only, so far.

- [x] `cudatoolkit`  - see https://github.com/conda-forge/cudatoolkit-feedstock/pull/53
- [x] Docker image (maybe just rebuild) @ `docker-images` -- see https://github.com/conda-forge/docker-images/pull/175
- [x] Windows installer @ `conda-forge-ci-setup` -- see https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/143

## Docs

- [x] Add note to explain how to expand the build matrix for users that want the full range 9.2-11.2.  - see https://github.com/conda-forge/conda-forge.github.io/pull/1262

**Comment by jaimergp** [comment]
The migration has started! 🎉 

We need to update the docs to point out how to expand the build matrix if the maintainer wants to opt-in for an all-manual mode. In the meantime, these PRs show how to do it:

* https://github.com/conda-forge/nvcc-feedstock/pull/64
* https://github.com/conda-forge/openmm-feedstock/pull/47

**Comment by jaimergp** [comment]
We can close this now that all the mentioned PRs were closed 🥳
