### ISSUE TITLE
Tracking issue for CUDA 11.5

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/cudatoolkit-feedstock#67]
Not sure how this is going to look like now that we have the enhanced compatibility [setup](https://github.com/conda-forge/nvcc-feedstock/pull/71), but still opening this because I've been looking forward to the `cuda-python` [bindings](https://github.com/NVIDIA/cuda-python), and it seems that @jakirkham et al. were busy publishing them for launch [already](https://github.com/conda-forge/cuda-python-feedstock)! 🥳 

## 11.5
Copied the list form #58, but I'm guessing not all will be necessary.
* [x]  https://github.com/conda-forge/cudatoolkit-feedstock/pull/68
* [x]  https://github.com/conda-forge/docker-images/pull/198
* [x]  https://github.com/conda-forge/nvcc-feedstock/pull/74
* [x]  https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/154
* [ ]  Migrator - unnecessary?

Xref #62

CC @jakirkham @leofang @jaimergp

**Comment by jaimergp** [comment]
We might need the build-time stuff (nvcc, images, ci-setup) for those (*) that cannot rely on CEC. 

(*) I don't really know if there are any feedstocks in this situation.

**Comment by jakirkham** [comment]
Looks like all of these are complete. There is an issue we need to follow up on for the Docker images ( https://github.com/conda-forge/docker-images/issues/205 ), but that depends on upstream and can be tracked separately

**Comment by jakirkham** [comment]
The Docker image issue has also been fixed. Going to go ahead and close this out. Thanks all! 😄
